#####
#
# This BOSHConfig contains our generic cloud configuration, to
# let BOSH know where our AZs map to at an IaaS layer, what
# GCP networks and subnetworks exist, how to number VMs, etc.
#
#####
---
apiVersion: gluon.starkandwayne.com/v1alpha1
kind: BOSHConfig
metadata:
  name:      cloud-config
  namespace: please-dont-apply-this-yaml

spec:
  type:     cloud      # this is a cloud config
  director: example1   # who do we apply the config to?

  config: |
    # This *looks* like YAML, but its really a multi-line
    # string, which will be placed into a file to be uploaded
    # as-is to our BOSH director...
    #
    azs:
      - name: z1
        cloud_properties: { zone: us-east1-b }
      - name: z2
        cloud_properties: { zone: us-east1-c }
      - name: z3
        cloud_properties: { zone: us-east1-d }

    vm_types:
      - name: default
        cloud_properties:
          cpu:  2
          ram:  2048
          disk: 8192

    compilation:
       az: z1
       network: default
       reuse_compilation_vms: true
       vm_type: default
       workers: 5

    networks:
      - name: default
        type: manual
        subnets:
          - range:   10.10.3.0/20
            gateway: 10.10.3.1
            azs: [z1,z2,z3]
            dns: [8.8.8.8, 8.8.4.4]
            cloud_properties:
              network_name: default
              tags: [vault]
            reserved:
              - 10.10.3.2 - 10.10.3.5
              - 10.10.3.21
            static:
              - 10.10.3.200 - 10.10.3.254
