---
apiVersion: gluon.starkandwayne.com/v1alpha1
kind: BOSHDeployment
metadata:
  name:      example1
namespace: please-dont-apply-this-yaml
spec:
  repo:       https://github.com/cloudfoundry/bosh-deployment
  ref:        master
  entrypoint: bosh.yml
  ops:
    - gcp/cpi.yml
    - jumpbox-user.yml
  vars:
    - configMap:
        name: bosh-vars
    - secret:
        name: gcp-creds
    - name:  internal_ip
      value: 10.10.3.21

---
apiVersion: v1
kind: ConfigMap
metadata:
  name:      bosh-vars
  namespace: please-dont-apply-this-yaml
data:
  internal_cidr: 10.10.3.0/24
  internal_gw:   10.10.3.1
  project_id:    your-gcp-project-id
  zone:          a-gcp-zone
  network:       default
  subnetwork:    default
  tags:         '[bosh, bosh-director]'

---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-creds
stringData:
  gcp_credentials_json: CHANGEME
